
linters:
  disable-all: true
  enable:
    - copyloopvar
    - durationcheck
    - errcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - examples
    - test-published
