
version: "2"

linters:
  enable:
    - copyloopvar
    - durationcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
