
version: "2"

linters:
  enable:
    - copyloopvar
    - durationcheck
    - forcetypeassert
    - godot
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - predeclared
    - staticcheck
    - unconvert
    - unparam
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - examples
    - test-published
  exclude-rules:
    - path: internal/client/client.go
      linters:
        - errcheck
      text: "Error return value of `.*\\.Body\\.Close` is not checked"
